### PR TITLE
Add usage exmple to README

### PR DESCRIPTION
**Pull request by trevorki**

### CODE REVIEW

**Comment by mikelynch416** [comment]
Can we also add ggplot2 as a dependency? I think Hazel was using that one

**Comment by trevorki** [comment]
OK good point

**Comment by trevorki** [comment]
had to change a bunch of dependencies so will do over

**Comment by trevorki** [comment]
oops... classic Kinsey git flub. PR is back

**Review by mikelynch416 — APPROVED** [review]
All good now, thanks Trevor

**Pull request merged**
